[package]
name = "texter"
version = "0.1.0"
edition = "2021"

[dependencies]
lsp-types = { version = "0.97.0", optional = true }
memchr = "2.7.4"

[features]
default = ["lsp-types"]
lsp-types = ["dep:lsp-types"]
