name: Run tests
run-name: ${{ github.ref }} 
on: 
  pull_request:
    types: [opened, edited]
  push:
    types: []

jobs:
  cargo_test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo test --all-features
